### ISSUE TITLE
提供现代汉语词典（第五版）中的词语列表

### ISSUE THREAD

**Issue by EsuRt** [wuhgit/CustomPinyinDictionary#1]
列表是从现代汉语词典（第五版）.mdx提取出来的，已去除音调，去除中文和英文以外的其他多余字符，并做了去重处理，词语和拼音应该比较准确，mdx资源来自网络。除该词典外，其他的汉语词典也同样能提取，有兴趣可以研究下。
[现代汉语词典（第五版）.txt](https://github.com/wuhgit/CustomPinyinDictionary/files/5646994/default.txt)

**Comment by wuhgit** [comment]
> 列表是从现代汉语词典（第五版）.mdx提取出来的，已去除音调，去除中文和英文以外的其他多余字符，并做了去重处理，词语和拼音应该比较准确，mdx资源来自网络。除该词典外，其他的汉语词典也同样能提取，有兴趣可以研究下。
> [现代汉语词典（第五版）.txt](https://github.com/wuhgit/CustomPinyinDictionary/files/5646994/default.txt)

感谢提供
