### ISSUE TITLE
能否制作一份小鹤双拼版呢

### ISSUE THREAD

**Issue by SunflowerThom** [wuhgit/CustomPinyinDictionary#11]
如题，双拼用户虽然不多，但还是有少量人在坚持。希望作者大大帮忙做一份，并不复杂。或者每次版本更新留一个txt词库文件，谢谢

**Comment by wuhgit** [comment]
请问你是用的什么输入法呢？

如果是 fcitx，双拼可以直接使用这个词库。
如果是 gboard，由于应用的种种限制加上这个词库的实现形式，双拼的支持暂时不会考虑。

txt文件你可以自己转换，之前有人提及过这个了，但如果是用在gboard,你可以先放弃了，因为应用限制它并不能导入这么大容量的txt词库。

**Comment by SunflowerThom** [comment]
谢谢回复 我用的是Gboard 双拼除了去搜狗官网扒一些词库没有系统的 之前提这个lssues的应该也是我 找了很久都没有找到合适的 打扰您了。

**Comment by wuhgit** [comment]
……抱歉，本来说把之前那个转换 txt 的 issues转告给你，然后发现就是你提及的。

我详细解释一下为什么这个词库在 gboard 当前情况下无法支持双拼吧。

现在这个词库其实只能算作自定义短语，gboard 包括之前的 谷歌拼音输入法 的词库都不是以这种形式存在的，原有词库不仅容量很小，无法容纳这么大的词量，在使用过程中还会不断加入用户自己的输入，造成原有词汇的丢失甚至于整个词库被清空，如果想要装下这么多词，只能使用现在这种方式。

这也就造成了另外的问题，包括但不限于双拼无法使用，打字出现莫名其妙的断字等。

之前因为我不了解双拼，一直也以为双拼需要另外的词库支持，但前段时间使用 fcitx 后发现并不是这样，准确来说双拼和全拼都是用的同一个词库，双拼只是全拼的另一种键盘映射而已。

如果你很在意双拼的使用，我可以建议你使用一下我提到的 fcitx ，配合我这个词库，输入体验其实很好，包括但不限于双拼。
目前来说这个输入法还处于开发状态，跟 gboard 相比也缺少了非常多的功能，但至少在基础输入上我觉得体验以及很不错了，现在它也是我常用的输入法，gboard 作为后备使用。

希望我这个解答你能够满意。

**Comment by SunflowerThom** [comment]
> ……抱歉，本来说把之前那个转换 txt 的 issues转告给你，然后发现就是你提及的。
> 
> 我详细解释一下为什么这个词库在 gboard 当前情况下无法支持双拼吧。
> 
> 现在这个词库其实只能算作自定义短语，gboard 包括之前的 谷歌拼音输入法 的词库都不是以这种形式存在的，原有词库不仅容量很小，无法容纳这么大的词量，在使用过程中还会不断加入用户自己的输入，造成原有词汇的丢失甚至于整个词库被清空，如果想要装下这么多词，只能使用现在这种方式。
> 
> 这也就造成了另外的问题，包括但不限于双拼无法使用，打字出现莫名其妙的断字等。
> 
> 之前因为我不了解双拼，一直也以为双拼需要另外的词库支持，但前段时间使用 fcitx 后发现并不是这样，准确来说双拼和全拼都是用的同一个词库，双拼只是全拼的另一种键盘映射而已。
> 
> 如果你很在意双拼的使用，我可以建议你使用一下我提到的 fcitx ，配合我这个词库，输入体验其实很好，包括但不限于双拼。 目前来说这个输入法还处于开发状态，跟 gboard 相比也缺少了非常多的功能，但至少在基础输入上我觉得体验以及很不错了，现在它也是我常用的输入法，gboard 作为后备使用。
> 
> 希望我这个解答你能够满意。

谢谢您，我会去尝试您提供的宝贵建议，虽然Gboard使用了很多年，但是它由最初上手时的惊叹到现在因为词库缺失成为影响输入效率的元凶，这么多年除了外观改进内核几乎没有大的变化，而且需要的隐私权限越来越多。您说的fcitx方案很早就听说过，但是一直没有下定决心，这次会尽力适应它，感谢您的真诚解答🙏
