### ISSUE TITLE
建议提供txt的词库文件，供直接导入Android

### ISSUE THREAD

**Issue by mingchau** [wuhgit/CustomPinyinDictionary#13]
最近重置了手机新装了Gboard，找到这个词库，非常感谢开发者的分享。
但是手机没有root，不能直接使用。然后尝试了Fcitx 5安卓版，导入很快，但是输入法整体上体验还不够好。

经过一番搜寻，发现了一个第三方的App，这个App可以导入txt词库，写入Android用户词典。
尝试把词库转成txt了，最终导入成功，122万词库，耗时70分钟
（小米10，MIUI13，为了避免锁屏导入中断，我开了个抖音循环播放，把这个App通过小窗运行在上层）

因此建议开发者可以提供一下txt词库，方便其他没有root的用户使用。
App地址：https://play.google.com/store/apps/details?id=com.usr.dict.mgr
附上今天转的词库：
[Gboard词库.zip](https://github.com/wuhgit/CustomPinyinDictionary/files/9542362/Gboard.zip)

**Comment by wuhgit** [comment]
没有 txt 词库不是我擅自给未root的用户做主，而是真的没有必要。

您也提到了，122万词库导入耗时70分钟。

按照现在这个词库的更新频率，即便是很多天更新一次，如果我作为用户，我不认为我有这个耐心每次都花这么长的时间来做这种事情，并且这种等待未必每次都能成功。

就算耗时只需要7分钟，这种耗时的事情也是毫无必要，因为得到的词库数据根本不完整。

你可以测试一下，如果是未 root ，有一个简单的方式可以验证，导入前记录一下 Gboard 应用信息里的存储空间占用，导入后记录一下，你会发现空间占用的确有所增加，但等使用一段时间后再比较一次，你会发现它又减小到接近最初的状态。
具体的原因，我在置顶的 issues 中有写，您可以看一下 https://github.com/wuhgit/CustomPinyinDictionary/issues/12 

---

对比一下现在通过模块进行安装的方式，进行安装或者更新只要几秒钟，结果的成功率非常高，不满意了重置或者卸载也非常方便，随时都可以进行。

两种方法的优劣显而易见，唯一的缺点就是这样的速度和易用性需要 root  ，但凡事总是有取舍的……

**Comment by wuhgit** [comment]
不过您这个提议也提醒了我，我在置顶的 issue 中的确没有标明 txt词库 的问题

**Comment by mingchau** [comment]
用那个App导入的时候，有一个进度条，看到最后导入的总数是一致的。
你说的这个过段时间词典数据会丢失的问题，之前没有留意过，我会再观察一下。

我个人的使用习惯是，设置好了可能一两年都不会再去重置手机和输入法了，所以一次性花70分钟我觉得还OK。
如果是经常折腾的话，确实是太费劲了

**Comment by skw2022** [comment]
> 最近重置了手机新装了Gboard，找到这个词库，非常感谢开发者的分享。 但是手机没有root，不能直接使用。然后尝试了Fcitx 5安卓版，导入很快，但是输入法整体上体验还不够好。
> 
> 经过一番搜寻，发现了一个第三方的App，这个App可以导入txt词库，写入Android用户词典。 尝试把词库转成txt了，最终导入成功，122万词库，耗时70分钟 （小米10，MIUI13，为了避免锁屏导入中断，我开了个抖音循环播放，把这个App通过小窗运行在上层）
> 
> 因此建议开发者可以提供一下txt词库，方便其他没有root的用户使用。 App地址：https://play.google.com/store/apps/details?id=com.usr.dict.mgr 附上今天转的词库： [Gboard词库.zip](https://github.com/wuhgit/CustomPinyinDictionary/files/9542362/Gboard.zip)

这个工具看来不错！
短语的话，gboard已经提供了；
词库的导入导出，主要用在换手机、或者换输入法的时候，以免出现词库断片的情况；
词库主要还是因人而异，靠养、个人积累。

**Comment by peter810819** [comment]
你是用什么工具转成txt的？
