### ISSUE TITLE
db文件转换为其他词库文件

### ISSUE THREAD

**Issue by 656399968** [wuhgit/CustomPinyinDictionary#14]
请问有不有办法将db文件转换为其他可导入的词库文件再使用到mac设备

**Comment by wuhgit** [comment]
能详细描述一下吗？什么形式的词库文件，mac设备上又是什么软件使用？

**Comment by 656399968** [comment]
「TextReplacements(1).db」https://www.aliyundrive.com/s/5i2F5JtGAcK
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
就是这个文件 这个是苹果手机用的 Mac需要用深蓝词库转换助手将其他词库文件转换成mac的 所以只要能够将这个数据库文件里面的词库转换成百度 搜狗之类的词库文件应该就可以再次转换 再在mac上使用

**Comment by wuhgit** [comment]
你不用转百度搜狗之类的，先转换成txt格式，然后再用深蓝转换就可以了。

转换的方法可以参考一下 [issue/6](https://github.com/wuhgit/CustomPinyinDictionary/issues/6)
也可以看看 [issue/13](https://github.com/wuhgit/CustomPinyinDictionary/issues/13) ，里面有已经转换好的txt格式词库，只是数据不是最新的。

我刚刚搜了一下，深蓝转换作者有说“Mac的自定义短语支持的量有限”，由于我没有苹果设备，所以没办法测试可行性如何，你可以试试。

**Comment by 656399968** [comment]
好的 晚点回去试试 谢谢你啦

**Comment by 656399968** [comment]
还有一个问题就是我看你发的那个是dict格式的 和这个数据库文件db是一样的通用转换的吗 因为这个db文件是别人分享出来的 但是这个词库也是很多的

**Comment by wuhgit** [comment]
我发的这个 dict 是 Fcitx5 用的词库格式，这个输入法是用在 Linux 或者 Android 上的。

词库和词库之间不一定能够通用转换，但如果都支持txt导出和导入就肯定是没问题的，只是多了一个步骤而已。

**Comment by 656399968** [comment]
好的 我回去看看
