### ISSUE TITLE
最近几版安装更新失败，提示未检测到Gboard

### ISSUE THREAD

**Issue by xydche** [wuhgit/CustomPinyinDictionary#16]
按音量+后提示未检测到Gboard，然后安装失败。
之前更新都没问题，现在手机上在用的是v20220929，十月份的更新失败

**Comment by wuhgit** [comment]
v20220929 之后只有当前这一个版本 v20221006，由于添加了多用户支持，改变了相关的检测模式，但你的描述说最近几版安装更新失败，能提供更详细的信息吗，比如 Gboard 版本，Android 系统版本，Magisk 版本等，我这边好排查一下

**Comment by xydche** [comment]
> v20220929 之后只有当前这一个版本 v20221006，由于添加了多用户支持，改变了相关的检测模式，但你的描述说最近几版安装更新失败，能提供更详细的信息吗，比如 Gboard 版本，Android 系统版本，Magisk 版本等，我这边好排查一下

可能是我看错版本了，总之0929之后的版本识别不到我手机上的gboard
一加7T 
系统oos10.3.8,安卓10
Magisk 25.2
Gboard 信息如下图
![Screenshot_20221011-190556](https://user-images.githubusercontent.com/14014356/195075081-89d8ee2d-3203-465c-ab31-4908796b4eae.jpg)

**Comment by wuhgit** [comment]
v20221006 更改了检测方式，但按照你这个截图的信息，现在检测的正好是这个路径，这就很奇怪了……

**Comment by wuhgit** [comment]
试试刚刚更新的 1012 这个版本，看看问题修复了没有。

**Comment by xydche** [comment]
> 

依旧，提示“用户主用户未检测到Gboard，已跳过安装。。。。”

**Comment by wuhgit** [comment]
你用 adb shell 执行一下这个命令，看看输出是什么

`ls -n /data/user/0 | grep "com.google.android.inputmethod.latin" | awk '{print $3}'`

可能需要先执行 `su` 提权

**Comment by xydche** [comment]
> 
返回如下
`10224`

**Comment by wuhgit** [comment]
如果是这样，不应该安装失败啊。

我发了一个测试模块

https://github.com/wuhgit/CustomPinyinDictionary/releases/download/assets/DEBUG_FOR_MAGISK.zip

麻烦安装一下并提供模块所输出的截图，这个模块不会被成功安装。

**Comment by xydche** [comment]
![Screenshot_20221012-151322](https://user-images.githubusercontent.com/14014356/195274767-f40c3d2e-9d22-43c7-876e-09e15ff83118.jpg)

**Comment by wuhgit** [comment]
按理说不应该这样，你刚刚使用 adb shell 执行的命令和我模块里面的识别命令是同一个，模块应该也可以正常识别并安装的，请问你这段时间有添加别的模块吗？我怀疑是不是有什么系统属性被修改了。

**Comment by wuhgit** [comment]
如果你现在重新安装 v20220929 ，能够安装成功吗？

**Comment by wuhgit** [comment]
也有可能是数据加密的问题，识别的时候无法匹配到对应的数据，我修改了刚刚的测试模块，如果方便，麻烦重新下载这个模块再贴个图看一下。

**Comment by xydche** [comment]
![Screenshot_20221012-184159](https://user-images.githubusercontent.com/14014356/195322359-2ec6e5ae-7331-46e5-ad51-68db17605db9.jpg)

**Comment by xydche** [comment]
我把手机重刷了一个全量包，还是不行，但是0929的又刷了一次没问题

**Comment by wuhgit** [comment]
能检测到备份文件，但检测不到Gboard的UID，这种情况的确很奇怪

**Comment by wuhgit** [comment]
我更换了检测方法，又更新了一版 v20221012 , 你重新下载后试试。

**Comment by xydche** [comment]
Ok了，已更新👍
