### ISSUE TITLE
如何导入

### ISSUE THREAD

**Issue by Eyion** [wuhgit/CustomPinyinDictionary#17]
现用同文输入法的四叶草九宫格方案，不知该如何导入贵词库？

**Comment by wuhgit** [comment]
把 fcitx 词库先转 txt 再转 yaml 就可以了

**Comment by Eyion** [comment]
是用深蓝词库转换吗？
![图片](https://user-images.githubusercontent.com/26318038/199219424-0919f4da-9bca-4098-99eb-f7fdc2c4f8ae.png)
左边是选自定义，右边选txt，转完再用这个txt转中州韵？
![图片](https://user-images.githubusercontent.com/26318038/199219731-bc3eead8-c17e-43ef-b0a3-5408db3fb93a.png)

**Comment by wuhgit** [comment]
https://github.com/wuhgit/CustomPinyinDictionary/issues/6

https://www.fkxxyz.com/d/cloverpinyin/#%E5%AF%BC%E5%85%A5%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%BA%93

**Comment by Eyion** [comment]
谢谢，安卓端是否跟win端一样操作？
魔改版会不会好配置些？

**Comment by wuhgit** [comment]
没用过同文输入法，所以这个只有你自己试一试才知道了

**Comment by wuhgit** [comment]
看样子应该是你某一处的操作出错了，能说一下你的步骤吗？越详细越好。

**Comment by Eyion** [comment]
（1）选择你的词库文件，截图如下
![01](https://user-images.githubusercontent.com/26318038/199511626-2319b113-e251-4d55-9799-c1baf24d6e23.jpg)
（2）选择转换类型（先由自定义转成txt，然后由txt转成中州韵），截图如下
![02](https://user-images.githubusercontent.com/26318038/199512240-cf7ea3ab-5933-49b0-b45e-3cf8357dd52f.jpg)
![03](https://user-images.githubusercontent.com/26318038/199513094-842268ea-6ca9-4cb7-a388-9cbc272eb9b4.jpg)

有可能出错的感觉是第1次转换类型选的自定义，但也不知道选其他什么更合适。或者我漏了什么步骤？

**Comment by wuhgit** [comment]
为什么要选自定义？……我给你的那两个链接你没看吗……

**Comment by Eyion** [comment]
那些有点复杂，没懂

**Comment by wuhgit** [comment]
其中第二个链接就是你用的四叶草方案的作者所提供的，另外该方案在 Github 项目的 wiki 页面也提供了相关的教程，你按照你自己的需求跟着来就可以了。

**Comment by Eyion** [comment]
我再研究研究
