### ISSUE TITLE
为保证性能和准确性，建议提供Gboard的用户词典(user_dict_3_3)格式

### ISSUE THREAD

**Issue by Marukon** [wuhgit/CustomPinyinDictionary#2]
user_dict_3_3格式的词典可以避免出现奇怪拆字、常见词词频被放到后面等问题。

制作方法：使用深蓝词库转换将词库转换为谷歌拼音格式，在谷歌拼音输入法中导入自定义词库，root手机后将user_dict_3_3复制出来即可。

**Comment by wuhgit** [comment]
我记得使用 user_dict_3_3 会丢词，一段时间后整个词库都空了……

**Comment by Marukon** [comment]
> 我记得使用 user_dict_3_3 会丢词，一段时间后整个词库都空了……

以前好像是有这个问题，最新的版本还暂未复现。
能麻烦作者大大提供一下user_dict_3_3版本方便选择吗？谢谢。

**Comment by wuhgit** [comment]
> > 我记得使用 user_dict_3_3 会丢词，一段时间后整个词库都空了……
> 
> 以前好像是有这个问题，最新的版本还暂未复现。
> 能麻烦作者大大提供一下user_dict_3_3版本方便选择吗？谢谢。

试了一下，谷歌拼音无法导入这个数量的词库……

**Comment by Marukon** [comment]
好吧，那太遗憾了。
