### ISSUE TITLE
请问rime怎么用？

### ISSUE THREAD

**Issue by plokid** [wuhgit/CustomPinyinDictionary#22]

**Comment by wuhgit** [comment]
目前没有提供 Rime 格式的词库，如果你要用，可以自己转换，大致流程应该是：

`dict > txt > yaml`

**Comment by plokid** [comment]
打了个包 https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary

**Comment by 4SM** [comment]
> 打了个包 [https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary ](https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary)

这个怎么下载？

**Comment by plokid** [comment]
> > 打了个包 [https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary ](https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary)
> 
> 这个怎么下载？

用这个工具转换
https://github.com/studyzy/imewlconverter

**Comment by 4SM** [comment]
> > > 打了个包   [https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary   ](https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary)
> > 
> > 
> > 这个怎么下载？
> 
> 用这个工具转换 [https://github.com/studyzy/imewlconverter ](https://github.com/studyzy/imewlconverter)

深蓝选那种词库？DICT 格式的？谢谢。

**Comment by 4SM** [comment]
小狼毫可以选中州韵。那 dict 格式的应该选择？

**Comment by plokid** [comment]
> 小狼毫可以选中州韵。那 dict 格式的应该选择？

  libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict temp.txt
  imewlconverter -i:libpy temp.txt -o:rime CustomPinyinDictionary.dict.yaml

**Comment by 4SM** [comment]
> 

😂 怎么弄，不会呀

**Comment by 4SM** [comment]
> > 小狼毫可以选中州韵。那 dict 格式的应该选择？
> 
> libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict temp.txt imewlconverter -i:libpy temp.txt -o:rime CustomPinyinDictionary.dict.yaml

好兄弟，我太喜欢这个词库了，就是不知道怎么用？求求你教教我。

**Comment by plokid** [comment]
> > > 小狼毫可以选中州韵。那 dict 格式的应该选择？
> > 
> > 
> > libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict temp.txt imewlconverter -i:libpy temp.txt -o:rime CustomPinyinDictionary.dict.yaml
> 
> 好兄弟，我太喜欢这个词库了，就是不知道怎么用？求求你教教我。

这个词库是fcitx5格式的，如果你用的是linux系统就安装fcitx5后运行上面的命令就行；如果是用windows或macos我也不知道怎么办，目前深蓝词库转换也不支持

**Comment by 4SM** [comment]
> > > > 小狼毫可以选中州韵。那 dict 格式的应该选择？
> > > 
> > > 
> > > libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict temp.txt imewlconverter -i:libpy temp.txt -o:rime CustomPinyinDictionary.dict.yaml
> > 
> > 
> > 好兄弟，我太喜欢这个词库了，就是不知道怎么用？求求你教教我。
> 
> 这个词库是fcitx5格式的，如果你用的是linux系统就安装fcitx5后运行上面的命令就行；如果是用windows或macos我也不知道怎么办，目前深蓝词库转换也不支持

你不是转换了一个吗？https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary 词库文件都是通用的。

**Comment by plokid** [comment]
> > > > > 小狼毫可以选中州韵。那 dict 格式的应该选择？
> > > > 
> > > > 
> > > > libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict temp.txt imewlconverter -i:libpy temp.txt -o:rime CustomPinyinDictionary.dict.yaml
> > > 
> > > 
> > > 好兄弟，我太喜欢这个词库了，就是不知道怎么用？求求你教教我。
> > 
> > 
> > 这个词库是fcitx5格式的，如果你用的是linux系统就安装fcitx5后运行上面的命令就行；如果是用windows或macos我也不知道怎么办，目前深蓝词库转换也不支持
> 
> 你不是转换了一个吗？https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary 词库文件都是通用的。

这个是aur的包，是archlinux用的

**Comment by plokid** [comment]
> > > > > 小狼毫可以选中州韵。那 dict 格式的应该选择？
> > > > 
> > > > 
> > > > libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict temp.txt imewlconverter -i:libpy temp.txt -o:rime CustomPinyinDictionary.dict.yaml
> > > 
> > > 
> > > 好兄弟，我太喜欢这个词库了，就是不知道怎么用？求求你教教我。
> > 
> > 
> > 这个词库是fcitx5格式的，如果你用的是linux系统就安装fcitx5后运行上面的命令就行；如果是用windows或macos我也不知道怎么办，目前深蓝词库转换也不支持
> 
> 你不是转换了一个吗？https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary 词库文件都是通用的。

[dict.zip](https://github.com/wuhgit/CustomPinyinDictionary/files/12556350/dict.zip)

**Comment by 4SM** [comment]
> > > > > > 小狼毫可以选中州韵。那 dict 格式的应该选择？
> > > > > 
> > > > > 
> > > > > libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict temp.txt imewlconverter -i:libpy temp.txt -o:rime CustomPinyinDictionary.dict.yaml
> > > > 
> > > > 
> > > > 好兄弟，我太喜欢这个词库了，就是不知道怎么用？求求你教教我。
> > > 
> > > 
> > > 这个词库是fcitx5格式的，如果你用的是linux系统就安装fcitx5后运行上面的命令就行；如果是用windows或macos我也不知道怎么办，目前深蓝词库转换也不支持
> > 
> > 
> > 你不是转换了一个吗？https://aur.archlinux.org/packages/rime-custom-pinyin-dictionary 词库文件都是通用的。
> 
> 这个是aur的包，是archlinux用的

太遗憾了。就没有办法把 dict 转成 txt 或者 yaml 吗？ ☹
