### ISSUE TITLE
magisk词库不支持kernelsu

### ISSUE THREAD

**Issue by David-plz** [wuhgit/CustomPinyinDictionary#23]
在ksu管理器下安装magisk词库，谷歌拼音字典里有词，但管理器显示不出来模块，希望后续能改进一下

**Comment by wuhgit** [comment]
因为这是一个 Magisk 模块，你只有用 Magisk 管理器才能显示模块。

按照我在 kernelsu 官方 FAQ 所了解到的情况，建议你安装 Magisk 管理器。

**Comment by David-plz** [comment]
> 因为这是一个 Magisk 模块，你只有用 Magisk 管理器才能显示模块。
> 
> 按照我在 kernelsu 官方 FAQ 所了解到的情况，建议你安装 Magisk 管理器。

好的已换回面具，多谢。

**Comment by wayner6** [comment]
现在已经能正常显示了

**Comment by wuhgit** [comment]
2024-05-17
模块已支持 KernelSu
