### ISSUE TITLE
[求助]

### ISSUE THREAD

**Issue by Crany-web** [wuhgit/CustomPinyinDictionary#24]
词库中缺少IP、DNS等词语有没有方法能让我自己加上去呢，否则每次跑来这儿麻烦你总归不好

**Comment by wuhgit** [comment]
不清楚你针对的是哪一个输入法，但我建议遇到这种英文词汇的时候还是切换到英文进行输入，又或者先切换大写然后直接输入对应字母后回车确认。
毕竟这只是一个中文词库，如果再添加上单词恐怕空间占用还要暴涨几个数量级，虽然我觉得这类单词也算常用，但没有这个必要。
