### ISSUE TITLE
使用~/.local/share/fcitx5/pinyin/dictionaries/替代/usr/share/fcitx5/pinyin/dictionaries/会更好

### ISSUE THREAD

**Issue by c4ys** [wuhgit/CustomPinyinDictionary#25]
/usr/share/fcitx5/pinyin/dictionaries/是系统目录，升级容易出现问题。

感谢分享的词库很不错。。。

**Comment by wuhgit** [comment]
嗯，理应是这样，只是我系统里有好几个用户，这样比较方便 😅，另外还要考虑 aur 安装的问题，就统一到这个目录了。
