### ISSUE TITLE
请提供一下已经转为.txt的词库，或者直接.zip可以安装到Gboard 的文件，谢谢

### ISSUE THREAD

**Issue by danieladg** [wuhgit/CustomPinyinDictionary#26]
如题，真的非常需要。现在的文件感觉很复杂，如果身边没电脑根本无法操作。目前直接导入是最方便的方式了。

**Comment by wuhgit** [comment]
@danieladg 
请看一下置顶的相关说明 https://github.com/wuhgit/CustomPinyinDictionary/issues/21
