### ISSUE TITLE
新版谷歌输入法导入导出格式已经调整，需要更新

### ISSUE THREAD

**Issue by mapleshadow** [wuhgit/CustomPinyinDictionary#28]
RT，还请更新。

**Comment by wuhgit** [comment]
我现在用的 Gboard 版本号是 `13.2.02.543712237-beta-arm64-v8a` ，根据我查到的信息，这个应该就是最新版，目前词库可以正常使用。

另外，能否描述一下导入导出格式做了什么调整？我没发现有什么需要更新的地方，而且导入导出格式和这个词库之间也没太大关系。

**Comment by mapleshadow** [comment]
[](url)
[PersonalDictionary-19.zip](https://github.com/wuhgit/CustomPinyinDictionary/files/12011265/PersonalDictionary-19.zip)
这是我导出的字典，空的，但可以看出格式与你的不一致。

**Comment by wuhgit** [comment]
……看样子你根本没有看过首页的说明介绍。

给 Gboard 用的词库是一个 Magisk 模块，使用根本不需要导入导出功能。

dict 文件是给 Fcitx5 用的，用途和格式完全不一样，要是能导入就奇怪了。

**Comment by wuhgit** [comment]
releases页面也有提示，`下载时请注意对应平台的文件名` ，你也没看见。

**Comment by wuhgit** [comment]
我再提示另一个地方，如果你想通过导入导出功能使用本词库，可以提前放弃，考虑到你这几处提示都没看见，估计置顶的 issue 你也没看过。

**Comment by mapleshadow** [comment]
> ……看样子你根本没有看过首页的说明介绍。
> 
> 给 Gboard 用的词库是一个 Magisk 模块，使用根本不需要导入导出功能。
> 
> dict 文件是给 Fcitx5 用的，用途和格式完全不一样，要是能导入就奇怪了。

我之前用的就是magisk模式，但我发现存在问题，就是输入法不认字典内容，不信你可以亲自试试。
正因为不认，我才手动导入，然后发现导入不了的问题。

**Comment by wuhgit** [comment]
看一下置顶的 [issue](https://github.com/wuhgit/CustomPinyinDictionary/issues/21) ，你的这些问题都有解答。
