### ISSUE TITLE
这是什么问题啊，

### ISSUE THREAD

**Issue by woshishiq1** [wuhgit/CustomPinyinDictionary#29]
装了Fcitx5安卓版了
![Screenshot_20230927-130130_Trebuchet](https://github.com/wuhgit/CustomPinyinDictionary/assets/90903172/72b78b42-e4a6-4228-a99f-4699393a406b)

**Comment by wuhgit** [comment]
这是因为你还没有使用过词库功能

fcitx 打开输入法设置 > 输入法  > 拼音 > 管理字典

然后再刷入模块就可以了
