### ISSUE TITLE
请问能提供纯文本格式的词库吗？

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [wuhgit/CustomPinyinDictionary#30]
放到小小输入法里

**Comment by wuhgit** [comment]
https://github.com/wuhgit/CustomPinyinDictionary/issues/21

如果还是需要 txt 格式的词库，比如用于其它输入法，可以通过 Fcitx 的词库进行转换：

- 下载 CustomPinyinDictionary_Fcitx_<版本号>.tar.gz 并解压，得到词库文件 CustomPinyinDictionary_Fcitx.dict
- Linux 下，安装 [libime](https://github.com/fcitx/libime)
- 在词库文件所在目录下使用命令 libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt 进行转换

**Comment by boomker** [comment]
> #21
> 
> 如果还是需要 txt 格式的词库，比如用于其它输入法，可以通过 Fcitx 的词库进行转换：
> 
> * 下载 CustomPinyinDictionary_Fcitx_<版本号>.tar.gz 并解压，得到词库文件 CustomPinyinDictionary_Fcitx.dict
> * Linux 下，安装 [libime](https://github.com/fcitx/libime)
> * 在词库文件所在目录下使用命令 libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt 进行转换

----

你好， 我在自己 Ubuntu 容器 环境下转 dict 格式词库文件到 txt 时发生了报错，如下图：
<img width="1438" alt="image" src="https://github.com/wuhgit/CustomPinyinDictionary/assets/19751472/f8e50272-28d1-4516-a70b-915d62afbfb1">

我之前也在容器环境里转过您的词典文件到 txt 格式，这次不知道是环境问题还是词典文件版本格式问题导致的。
翻了一下 issue，txt 格式的词典文件还是有需求的， 之前转到 txt 格式时，发现了一些注音错误， 想提 issue， 但项目没有提供 txt 格式，可能有些不方便。希望能提供 txt 格式，方便大家使用和找出其中的错误。

**Comment by wuhgit** [comment]
@boomker 

可能是 libime 版本的问题，最新的版本是1.1.5。

另外我也一直都在修订错误的拼音，但由于精力有限无法逐条修正，欢迎发 issue,  麻烦您直接指出错误的词条即可，我会在下一个版本中进行修正，因为我这边生成词库的整个流程都不需要 txt 格式，所以也不存在不方便一说。
