### ISSUE TITLE
能修改下脚本兼容KernelSU吗

### ISSUE THREAD

**Issue by kyle18th** [wuhgit/CustomPinyinDictionary#31]
现在[KernelSU](https://kernelsu.org/)越来越完善，用户也越来越多，尝试安装但是重启后模块就消失了，查看/data/adb/modules下CustomPinyinDictionary文件夹也没了。

**Comment by wuhgit** [comment]
https://github.com/wuhgit/CustomPinyinDictionary/issues/23

https://kernelsu.org/guide/faq.html

很遗憾目前没有这个打算，而且按照官方faq的说法，kernelsu的模块还处于早期开发的不稳定状态。

**Comment by wuhgit** [comment]
2024-05-17
模块已支持 KernelSu
