### ISSUE TITLE
请问下，通过magisk安装词库后，gboard的cpu占用都会非常高，过5分钟左右才会趋于正常

### ISSUE THREAD

**Issue by SandiTT** [wuhgit/CustomPinyinDictionary#34]
magisk 版本为 26.3
gboard 版本为最新googleplay版本
测试了两种场景：
一个是删除词库后重启，cpu占用只在5%左右
另一个是安装词库后，gboard的cpu占用高达300%多，杀掉进程后继续打开gboard依然会飙到200左右。重启手机后 cpu占用依然会超过100%。

安装完词库后，我看了下安装包下面的数据库内容，基本上字典值都已经存在了，难道是gboard在重建索引之类的吗。一开始我以为是插件有问题，后来想了想感觉还是软件的问题

**Comment by wuhgit** [comment]
CPU占用高是因为 Gboard 会在后台为数据生成`dict_3_3` 类型的词库，由于这个词库的数据量触发了上限，数据随时会被清空，而清空之后的某一次启动它又会开始自动生成……
具体详情可以参考一下 [置顶的issue](https://github.com/wuhgit/CustomPinyinDictionary/issues/21)

**Comment by boilfish** [comment]
> CPU占用高是因为 Gboard 会在后台为数据生成`dict_3_3` 类型的词库，由于这个词库的数据量触发了上限，数据随时会被清空，而清空之后的某一次启动它又会开始自动生成…… 具体详情可以参考一下 [置顶的issue](https://github.com/wuhgit/CustomPinyinDictionary/issues/21)

@wuhgit 请问这个情况现在在新版还存在吗，会不会对系统开销和续航造成很大影响？

**Comment by wuhgit** [comment]
> > CPU占用高是因为 Gboard 会在后台为数据生成`dict_3_3` 类型的词库，由于这个词库的数据量触发了上限，数据随时会被清空，而清空之后的某一次启动它又会开始自动生成…… 具体详情可以参考一下 [置顶的issue](https://github.com/wuhgit/CustomPinyinDictionary/issues/21)
> 
> [@wuhgit](https://github.com/wuhgit) 请问这个情况现在在新版还存在吗，会不会对系统开销和续航造成很大影响？

新版依旧存在，因为Gboard处理词库相关的流程并没有改变。

影响肯定是有的，毕竟浪费了很多计算和存储资源，还不止一次，因为每个人手机的硬件配置以及后台可用的空闲资源都不一样，相关的影响很难具体量化，只能是自己试过，评估一下得失再决定是否继续使用了。
