### ISSUE TITLE
平板没有音量键，无法安装magisk模块

### ISSUE THREAD

**Issue by jinshuqishi2019** [wuhgit/CustomPinyinDictionary#37]
我现在文石设备使用gboard，想导入你的magisk模块词库，发现需要按音量键+，但是本设备只有电源键和返回键，请问可以修改成直接安装的形式吗？

**Comment by wuhgit** [comment]
直接安装不便于模块管理，所以不会考虑这种形式。

如果设备没有音量键，可以换种方式，变通实现：

```
# 音量+
adb shell input keyevent 24

# 音量-
adb shell input keyevent 25
```

> 稍后我也会把这些命令添加补充到 ReadMe.md 里

**Comment by jinshuqishi2019** [comment]
adb shell input keyevent 24
使用上面命令确实可以调节音量，但是在magisk模块安装界面没有响应，不出现音量调节界面，即使多次输入命令，还是提示未检测到音量键，请再试一次，最后安装失败。

**Comment by wuhgit** [comment]
如果是这样，找一个虚拟音量键的应用试试，又或者通过类似 [QtScrcpy](https://github.com/barry-ran/QtScrcpy) 的电脑端应用进行远程操作。

**Comment by jinshuqishi2019** [comment]
尝试了几个虚拟音量键都是不行，后面想到可能需要实体按钮才行，想到有多媒体功能的键盘，接连上就可以识别了。

**Comment by wuhgit** [comment]
这个词库在 Gboard 上出现的问题比较多，详见 https://github.com/wuhgit/CustomPinyinDictionary/issues/21
