### ISSUE TITLE
导入失败，使用magisk刷入必须是24.0以上版本么？

### ISSUE THREAD

**Issue by gygzff** [wuhgit/CustomPinyinDictionary#39]
报错：! Please install Magisk v24.0+ (24000+)

导入词库失败,因为一直使用23版本，有hide。
所以很久没更新折腾这些了，现在必须更新版本才能使用么？
能不能兼容适合低版本的呢

**Comment by wuhgit** [comment]
是的，必须24以上。
Magisk 24也不是最新的啊，这已经是两年前就放出来的版本了。

友情建议：
如果你是想为了用 Gboard 词库而更新 Magisk ，应该先看看置顶的 issue ，因为后期问题比较多，这个折腾不一定值得。
如果你是用在 Fcitx5 上面，可以考虑手动安装，Magisk 模块只是为了方便日常更新而已，词库数据并无区别。

**Comment by gygzff** [comment]
> 是的，必须24以上。 Magisk 24也不是最新的啊，这已经是两年前就放出来的版本了。
> 
> 友情建议： 如果你是想为了用 Gboard 词库而更新 Magisk ，应该先看看置顶的 issue ，因为后期问题比较多，这个折腾不一定值得。 如果你是用在 Fcitx5 上面，可以考虑手动安装，Magisk 模块只是为了方便日常更新而已，词库数据并无区别。

好的！也对，确实是有点久的版本了，是时候折腾更新了‘，非常感谢😁
