### ISSUE TITLE
为什么有时候会把单个的汉字给强行拆成词语

### ISSUE THREAD

**Issue by StingGrey** [wuhgit/CustomPinyinDictionary#4]
![Screenshot_2021-11-24-18-46-17-980_com android chrome](https://user-images.githubusercontent.com/77520262/143224322-e53a24b2-c870-4e7d-8330-83fab8acf9d7.jpg)
![Screenshot_2021-11-24-18-46-22-131_com android chrome](https://user-images.githubusercontent.com/77520262/143224334-1617e69f-4d62-40a5-ac97-4814b776d56d.jpg)
很难受，求解🥲

**Comment by iliuyuyang** [comment]
哈哈，经常遇到，总结了下其实是Gboard智障，这问题原因我总结下来就是：你输入太快了。起码我现在实践下来是这原因。

**Comment by wuhgit** [comment]
> 很难受，求解

这个问题目前是无解的……

Gboard 在当前时间点并不支持词库数据中包含分词符（这个名称不一定准确，反正就是空格或者顿号之类的），当你输入 xiao 的时候，你可能是想输入 “小”， 此时它发现词库里有一个拼音被设置为 “xiao” 的词语，可这个词语的拼音本该是 “xi ao” 却因为不支持分词符只能被存储为“xiao”，但它并不知道，然后就把它当作提示显示出来了。

如果有一天它支持分词符了，这个问题应该就可以解决了。

相同的词库数据，在电脑端的 Fcitx5 中就表现得非常好，因为对于一个正常的中文拼音输入法而言，词库支持分词符是基础功能，然而……Gboard并不支持。
