### ISSUE TITLE
能否添加一下对kernelsu支持

### ISSUE THREAD

**Issue by xianchenl** [wuhgit/CustomPinyinDictionary#41]
虽然kernelsu可以刷magisk模块，但是不知道为什么，重启过后模块就会消失，不生效。不光是kernelsu管理器的重启,正常的重启手机模块也会消失

**Comment by wuhgit** [comment]
https://github.com/wuhgit/CustomPinyinDictionary/issues/23

**Comment by wuhgit** [comment]
2024-05-17
模块已支持 KernelSu
