### ISSUE TITLE
关于小企鹅输入法导入该词库后输入过快卡顿的问题

### ISSUE THREAD

**Issue by Onionfish2** [wuhgit/CustomPinyinDictionary#42]
单独安装该词库输入过快会导致输入法卡顿（慢一拍，但是使用zhwiki和萌娘百科的词库都无影响，三者同时导入词库还是会卡顿，取消custom词库后则一切正常，是该词库太大的原因吗？

**Comment by wuhgit** [comment]
如果单独使用有卡顿，那可以确定就是这个词库的问题了。

**Comment by Onionfish2** [comment]
> 如果单独使用有卡顿，那可以确定就是这个词库的问题了。

之前单独使用就是卡顿，一度以为是输入法问题，后来发现确实是词库导致的，望早日定位

**Comment by wuhgit** [comment]
这个问题恐怕无解，因为我无法复现你所描述的输入卡顿，日常唯一能感知到的卡顿只是在手机开机后首次打开输入法的时候。

声明一下我并不是要否认您的实际体验，也可能是我的输入速度不够快所以无法复现，我只能从其它方面帮你排查。

首先我可以排除是词库过大的问题，按照我刚刚做的统计，zhwiki 和 moegirl 这两个词库如果同时启用，它们合计提供的词条数量和数据容量已经超过了我的这个词库：

 - zhwiki-20240210 是 1366722 条，总计 43.8 MiB
 - moegirl-20231114 是 106392 条，总计 3.4 MiB
 - CustomPinyinDictionary-20240203 是 1451468 条，总计  40.0 MiB 

另外fcitx词库的转换生成的过程几乎一样，这也不会是造成卡顿的原因。

其次是手机硬件的问题，我现在用的手机还是五年前的型号，我不觉得你的手机会比它还老旧，因此也可以排除硬件的问题。

但我也认同我用着不卡顿不代表在其它手机上就不会卡顿，这个问题很复杂，加上我也完全无法通过你的输入速度来进行测试，我只能建议你再找另一个手机试一下，确认是不是其它原因造成的。

**Comment by WIGIW1314** [comment]
我也遇到了，导入了词库之后，打字快的时候会出现不跟手的情况
