### ISSUE TITLE
能否提供一份ios使用的词库

### ISSUE THREAD

**Issue by windy1lee** [wuhgit/CustomPinyinDictionary#43]
如题

**Comment by wuhgit** [comment]
是指 ios 上的 Gboard 吗？

**Comment by wuhgit** [comment]
如果是指 ios 上的 Gboard, ios 要写入应用私有数据需要越狱，这个词库在 android 这边有的问题它也会有，为一个不成熟的词库就付出这种代价有点夸张了。
如果是 fcitx, 据我目前所知好像还没有相关的 ios 版本，就算未来有了，词库应该也是通用的。

所以，这个问题是不能。
