### ISSUE TITLE
能否添加linux下智能拼音的支持

### ISSUE THREAD

**Issue by nan-mu** [wuhgit/CustomPinyinDictionary#44]
在ubuntu 22.04下似乎默认的中文输入法为智能拼音。有一些优点，但词库和联想机制实在拉胯。更逆天的是用户词库自创了一种读取方法导致本仓库的资源无法使用：

![image](https://github.com/wuhgit/CustomPinyinDictionary/assets/111669112/35d6a7ab-d094-4c87-a3fb-6f2a90b933de)

能否提供图中所描述的词库文件，或是提供给我一些关于.dict文件的解析方法，我愿意提交一份pr以适配智能拼音

**Comment by wuhgit** [comment]
> 请注意，因为我没有使用这个输入法，以下内容仅供参考

看截图中帮助提示的词典格式，其实你可以直接使用这个词库，但需要先转换为 txt 格式。

具体方法可以参考 https://github.com/wuhgit/CustomPinyinDictionary/issues/21

**Comment by nan-mu** [comment]
libime的安装一直没有成功...很奇怪，网上资料也不多
打算放弃了，找到了一些其他词库，谢谢
