### ISSUE TITLE
Ubuntu 将词库转换为txt文件教程

### ISSUE THREAD

**Issue by QPYIDRWIMG** [wuhgit/CustomPinyinDictionary#46]
1. 备份 `sources.list`：`cp /etc/apt/sources.list /etc/apt/sources.list.bak`
2. 编辑 `sources.list`：`nano /etc/apt/sources.list`
3. 将文件里的内容全部替换成以下内容：
```
# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse

# 预发布软件源，不建议启用
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse

```
4. 更新源：`apt update`
5. 安装 `libime-bin`：`apt install libime-bin`
6. 还原 `sources.list`：`cp /etc/apt/sources.list.bak /etc/apt/sources.list`
7. 下载 `CustomPinyinDictionary_Fcitx_<版本号>.tar.gz` 并解压，得到词库文件 `CustomPinyinDictionary_Fcitx.dict`
8. 进入词库文件所在目录，将词库转换为txt文件：`libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt`

**Comment by QPYIDRWIMG** [comment]
若命令受限于权限而无法执行，请在命令之前加上`sudo`

**Comment by Reweng** [comment]
> 1. 备份`sources.list`：`cp /etc/apt/sources.list /etc/apt/sources.list.bak`
> 2. 编辑`sources.list`：`nano /etc/apt/sources.list`
> 3. 将文件里的内容全部替换成以下内容：
> 
> ```
> # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse
> 
> # 预发布软件源，不建议启用
> # deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
> ```
> 
> 4. 更新来源：`apt update`
> 5. 安装`libime-bin`：`apt install libime-bin`
> 6. 还原`sources.list`：`cp /etc/apt/sources.list.bak /etc/apt/sources.list`
> 7. 下载`CustomPinyinDictionary_Fcitx_<版本号>.tar.gz`并解压，获取词库文件`CustomPinyinDictionary_Fcitx.dict`
> 8. 进入词库文件所在目录，将词库转换为txt文件：`libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt`

![屏幕截图 2024-04-25 052836](https://github.com/wuhgit/CustomPinyinDictionary/assets/41164901/d0c9564d-89a0-4d16-a6c1-c4eef9451a5e)
报错了

**Comment by Reweng** [comment]
> 1. 备份`sources.list`：`cp /etc/apt/sources.list /etc/apt/sources.list.bak`
> 2. 编辑`sources.list`：`nano /etc/apt/sources.list`
> 3. 将文件里的内容全部替换成以下内容：
> 
> ```
> # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse
> 
> # 预发布软件源，不建议启用
> # deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
> ```
> 
> 4. 更新来源：`apt update`
> 5. 安装`libime-bin`：`apt install libime-bin`
> 6. 还原`sources.list`：`cp /etc/apt/sources.list.bak /etc/apt/sources.list`
> 7. 下载`CustomPinyinDictionary_Fcitx_<版本号>.tar.gz`并解压，获取词库文件`CustomPinyinDictionary_Fcitx.dict`
> 8. 进入词库文件所在目录，将词库转换为txt文件：`libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt`

![屏幕截图 2024-04-25 053515](https://github.com/wuhgit/CustomPinyinDictionary/assets/41164901/ab5efe87-317f-4eed-a7cb-e93f52b556b4)
![屏幕截图 2024-04-25 053945](https://github.com/wuhgit/CustomPinyinDictionary/assets/41164901/0a8e5cfc-c8c5-4ccd-93e2-24b92dcc4507)
奇怪 怎么会报错的

**Comment by Reweng** [comment]
> 1. 备份`sources.list`：`cp /etc/apt/sources.list /etc/apt/sources.list.bak`
> 2. 编辑`sources.list`：`nano /etc/apt/sources.list`
> 3. 将文件里的内容全部替换成以下内容：
> 
> ```
> # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
> deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse
> 
> # 预发布软件源，不建议启用
> # deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
> ```
> 
> 4. 更新来源：`apt update`
> 5. 安装`libime-bin`：`apt install libime-bin`
> 6. 还原`sources.list`：`cp /etc/apt/sources.list.bak /etc/apt/sources.list`
> 7. 下载`CustomPinyinDictionary_Fcitx_<版本号>.tar.gz`并解压，获取词库文件`CustomPinyinDictionary_Fcitx.dict`
> 8. 进入词库文件所在目录，将词库转换为txt文件：`libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt`

root@LAPTOP-5BIIDFU8:/home/dict# libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Invalid pinyin version.
Aborted
报错了
