### ISSUE TITLE
KernelSu 重启后模块消失

### ISSUE THREAD

**Issue by JefferyW1** [wuhgit/CustomPinyinDictionary#47]
如题
KernelSu 重启后模块消失；

**Comment by wuhgit** [comment]
Magisk 模块与 KernelSu 模块有区别，我正在解决这个问题。

**Comment by wuhgit** [comment]
顺带说明一下，模块消失后数据仍旧存在，如果想要清理这些数据可以使用此模块内置的卸载。

**Comment by JefferyW1** [comment]
> 顺带说明一下，模块消失后数据仍旧存在，如果想要清理这些数据可以使用此模块内置的卸载。

怪不得看不到模块，但是 键盘词典里 还有词库数据

**Comment by wuhgit** [comment]
2024-05-17
问题已经修复
