### ISSUE TITLE
能不能直接提供一下其他主流输入法的词库格式啊？比如txt，搜狗的bin等

### ISSUE THREAD

**Issue by kulkatt** [wuhgit/CustomPinyinDictionary#50]
用深蓝词库转换工具试着转换，结果出错了。。。

**Comment by wuhgit** [comment]
txt格式的转换可以看置顶。

没有支持其它输入法的打算。

**Comment by NJYZ-96** [comment]
> txt格式的转换可以看置顶。
> 
> 没有支持其它输入法的打算。

 置顶教程需要使用Linux 系统，对普通用户要求太高了，难以实现。
有深蓝词库转换工具可以轻易完成词库格式转换，只需要您直接提供一份TXT文本词库即可；不会增加额外工作量；
如果担心会增加兼容性导致的大量提问，可以给一个免责声明，不对因此产生的问题进行维护；

不管怎样，感谢大佬付出

**Comment by NJYZ-96** [comment]
> > txt格式的转换可以看置顶。
> > 没有支持其它输入法的打算。
> 
> 置顶教程需要使用Linux 系统，对普通用户要求太高了，难以实现。 有深蓝词库转换工具可以轻易完成词库格式转换，只需要您直接提供一份TXT文本词库即可；不会增加额外工作量； 如果担心会增加兼容性导致的大量提问，可以给一个免责声明，不对因此产生的问题进行维护；
> 
> 不管怎样，感谢大佬付出

主要考虑到还有PC端win用户，微软拼音的词库也十分难用，有一个好用的第三方词库会很棒，不同格式间的转换现在也有现成工具：https://github.com/studyzy/imewlconverter 深蓝词库转换

**Comment by wuhgit** [comment]
@NJYZ-96 

深蓝词库已经可以转换 fcitx 的词库格式了，不用特意执著于非要一个txt格式来做中转。 https://github.com/studyzy/imewlconverter/pull/319

另外，微软拼音词库有上限，只有2万，而这个词库远超这个上限，所以也可以先放弃了，不现实。 https://www.cnblogs.com/studyzy/p/12638297.html

**Comment by NJYZ-96** [comment]
> @NJYZ-96
> 
> 深蓝词库已经可以转换 fcitx 的词库格式了，不用特意执著于非要一个txt格式来做中转。 [studyzy/imewlconverter#319](https://github.com/studyzy/imewlconverter/pull/319)
> 
> 另外，微软拼音词库有上限，只有2万，而这个词库远超这个上限，所以也可以先放弃了，不现实。 https://www.cnblogs.com/studyzy/p/12638297.html

@wuhgit 首先感谢回复，打扰了；

1、关于微软拼音词库限制，目前已知的是自学习词库的限制是两万条，但用户自定义短语目前并未明确有具体限制，网络信息中最多导入有600万条，只是会导致该项设置之后卡死无法打开，需要手动清除配置文件才能打开，但输入测试表明导入是生效的，我个人实际测试也是如此；

2、关于深蓝词库对fcitx的支持，目前并没有，issues中今年3月说的是[无计划](https://github.com/studyzy/imewlconverter/issues/302)，并建议使用Fcitx 的词库进行转换，但问题还是需要Linux 系统 ；至于你给的链接，没看懂，似乎没有相关性；

3、可以说说不愿意给TXT文件的顾虑是什么吗？这似乎不会增加什么工作量

**Comment by wuhgit** [comment]
@NJYZ-96 

如果我有顾虑，txt的转换方法我就不会置顶了，这只是个词库而已，不是什么机密。

**Comment by peqing** [comment]
> > @NJYZ-96
> > 深蓝词库已经可以转换 fcitx 的词库格式了，不用特意执著于非要一个txt格式来做中转。 [studyzy/imewlconverter#319](https://github.com/studyzy/imewlconverter/pull/319)
> > 另外，微软拼音词库有上限，只有2万，而这个词库远超这个上限，所以也可以先放弃了，不现实。 https://www.cnblogs.com/studyzy/p/12638297.html
> 
> @wuhgit 首先感谢回复，打扰了；
> 
> 1、关于微软拼音词库限制，目前已知的是自学习词库的限制是两万条，但用户自定义短语目前并未明确有具体限制，网络信息中最多导入有600万条，只是会导致该项设置之后卡死无法打开，需要手动清除配置文件才能打开，但输入测试表明导入是生效的，我个人实际测试也是如此；
> 
> 2、关于深蓝词库对fcitx的支持，目前并没有，issues中今年3月说的是[无计划](https://github.com/studyzy/imewlconverter/issues/302)，并建议使用Fcitx 的词库进行转换，但问题还是需要Linux 系统 ；至于你给的链接，没看懂，似乎没有相关性；
> 
> 3、可以说说不愿意给TXT文件的顾虑是什么吗？这似乎不会增加什么工作量

大佬 您有找到或者生成过微软输入法的词库吗？可以分享一份吗

**Comment by NJYZ-96** [comment]
> > > @NJYZ-96
> > > 深蓝词库已经可以转换 fcitx 的词库格式了，不用特意执着于非要一个txt格式来做中转。 [studyzy/imewlconverter#319](https://github.com/studyzy/imewlconverter/pull/319)
> > > 另外，微软拼音词库有上限，只有2万，而这个词库远超这个上限，所以也可以先放弃了，不现实。 [![此链接将前往内容农场](chrome-extension://lcghoajegeldpfkfaejegfobkapnemjl/img/content-farm-marker.svg)https://www.cnblogs.com/studyzy/p/12638297.html](https://www.cnblogs.com/studyzy/p/12638297.html)
> > 
> > 
> > @wuhgit 首先感谢回复，打扰了；
> > 1、关于微软拼音词库限制，目前已知的是自学习词库的限制是两万条，但用户自定义短语目前并未明确有具体限制，网络信息中最多导入有600万条，只是会导致该项设置之后卡死无法打开，需要手动清除配置文档才能打开，但输入测试表明导入是生效的，我个人实际测试也是如此；
> > 2、关于深蓝词库对fcitx的支持，目前并没有，issues中今年3月说的是[无计划](https://github.com/studyzy/imewlconverter/issues/302)，并建议使用Fcitx 的词库进行转换，但问题还是需要Linux 系统 ；至于你给的链接，没看懂，似乎没有相关性；
> > 3、可以说说不愿意给TXT文档的顾虑是什么吗？这似乎不会增加什么工作量
> 
> 大佬 您有找到或者生成过微软输入法的词库吗？可以分享一份吗

https://github.com/studyzy/imewlconverter/issues/321
看看这个试试

**Comment by NJYZ-96** [comment]
记不到了，深蓝是可以自定义的，你打开TXT格式的，看一下它的规则，用自定义模式也行

具体的去看深蓝的文档
