### ISSUE TITLE
你好，请问安卓gboard有可以通过shizuku添加词库的方式吗，现在的手机太难root了

### ISSUE THREAD

**Issue by WinsK1** [wuhgit/CustomPinyinDictionary#51]

**Comment by wuhgit** [comment]
据我当前的了解，shizuku只能获取部分系统权限，并不能修改第三方应用的数据文件。

**Comment by wuhgit** [comment]
另外，如果你不是非Gboard不可，要不试试 Fcitx 输入法，词库可以直接安装，就本词库而言，输入体验比Gboard好很多。

**Comment by yhx0022** [comment]
> 另外，如果你不是非Gboard不可，要不试试 Fcitx 输入法，词库可以直接安装，就本词库而言，输入体验比Gboard好很多。

我一般给fcitx5添加搜狗细胞词库中的“网络流行新词”。
https://pinyin.sogou.com/dict/detail/index/4?rf=dictindex
这个词库只有不到3000个词条。更新频率2到3天。

请问开发者你维护的词库里面，有包含这个“网络流行新词”吗？
如果有我就不自己另外添加了。

**Comment by wuhgit** [comment]
> > 另外，如果你不是非Gboard不可，要不试试 Fcitx 输入法，词库可以直接安装，就本词库而言，输入体验比Gboard好很多。
> 
> 我一般给fcitx5添加搜狗细胞词库中的“网络流行新词”。 https://pinyin.sogou.com/dict/detail/index/4?rf=dictindex 这个词库只有不到3000个词条。更新频率2到3天。
> 
> 请问开发者你维护的词库里面，有包含这个“网络流行新词”吗？ 如果有我就不自己另外添加了。


建议你还是保留，两者之间肯定会有重复的词条，但对于重复的内容，输入法自己会帮你处理好，没必要非得二选一，对于现在的设备性能而言，这点数据的处理压力可以忽略。

**Comment by miao-o** [comment]
我想请问下 如果直接用手机自带的换机等软件备份已使用magisk模块的gboard安装到非root手机上是不是可以把词库带过来

**Comment by wuhgit** [comment]
> 我想请问下 如果直接用手机自带的换机等软件备份已使用magisk模块的gboard安装到非root手机上是不是可以把词库带过来

理论上是可以，但每个品牌手机自带的换机备份可能有区别，这个你得试一下才知道。

我当前手机是类原生系统，使用类似 SwiftBackup 这样的应用备份，词库数据是包含在备份里面的，仅供参考。
