### ISSUE TITLE
Fcitx5-android Magisk 模块失效

### ISSUE THREAD

**Issue by so1ar** [wuhgit/CustomPinyinDictionary#52]
模块显示安装成功，但在软件里没有对应词库，在对应的文件夹里也找不到词库文件
![S40824-10591194_tl zp](https://github.com/user-attachments/assets/61043af7-bcf0-4919-84a8-69d3c580227e)
![S40824-11000506_org fcitx fcitx5 android](https://github.com/user-attachments/assets/e6971a21-c6d1-456f-9996-e6675b918b7c)

**Comment by wuhgit** [comment]
能否安装一下  `DEBUG_FOR_MAGISK.zip` 并提供一下过程截图？

**Comment by so1ar** [comment]
> 能否安装一下 `DEBUG_FOR_MAGISK.zip` 并提供一下过程截图？

![S40824-11204849_tl zp](https://github.com/user-attachments/assets/c5f06eed-e856-4259-9092-fe66039b9361)

**Comment by wuhgit** [comment]
你手机上是不是有很多用户啊？又或者fcitx有多个用户配置？
如果没有进行配置，模块默认只会为主用户进行安装。

**Comment by so1ar** [comment]
> 你手机上是不是有很多用户啊？又或者fcitx有多个用户配置？ 如果没有进行配置，模块默认只会为主用户进行安装。

我手机上没有搞过多用户啊

**Comment by wuhgit** [comment]
正常来说，不应该有这么多输出项的，我的输出是这样（忽略Gboard那一栏，Fcitx应该只会输出一项）：

![20240824-113241](https://github.com/user-attachments/assets/2e6d71c9-cd89-4f1a-b29c-707d78106b27)

😅 实在不行要不你还是选择手动安装吧……

**Comment by wuhgit** [comment]
补充一句，不管怎样，建议你再安装一次模块选择卸载，把之前安装到不知道哪里的词库先删除，免得浪费你手机的存储空间～

**Comment by so1ar** [comment]
> 正常来说，不应该有这么多输出项的，我的输出是这样（忽略Gboard那一栏，Fcitx应该只会输出一项）：

那就奇怪了，我 pm list users 一下，确实只有一个用户。

我试着重装一下 Fcitx5-android，看看能不能好，实在不行就手动安装吧。

**Comment by wuhgit** [comment]
多用户是一方面，单用户下也有可能是工作资料、个人资料、应用分身等等之类的问题，现在Android这方面有点混乱，原生和各家的系统都不太一致，很难说是哪里的问题。
总之就是模块探测到了多个位置，但它选了一个你当前没用使用的位置来安装词库并提示安装成功，所以你这边看不见词库。
这种情况下，选择手动安装应该是最稳妥的。

**Comment by so1ar** [comment]
> 多用户是一方面，单用户下也有可能是工作资料、个人资料、应用分身等等之类的问题，现在Android这方面有点混乱，原生和各家的系统都不太一致，很难说是哪里的问题。 总之就是模块探测到了多个位置，但它选了一个你当前没用使用的位置来安装词库并提示安装成功，所以你这边看不见词库。 这种情况下，选择手动安装应该是最稳妥的

我发现了，DEBUG 里 fcitx 多出来的几项是因为我安装了 fcitx5 更新器和几个插件，把插件和更新器都卸载之后，输出就只有一项了，但即便如此，安装模块后还是没有词库😂

**Comment by wuhgit** [comment]
> > 多用户是一方面，单用户下也有可能是工作资料、个人资料、应用分身等等之类的问题，现在Android这方面有点混乱，原生和各家的系统都不太一致，很难说是哪里的问题。 总之就是模块探测到了多个位置，但它选了一个你当前没用使用的位置来安装词库并提示安装成功，所以你这边看不见词库。 这种情况下，选择手动安装应该是最稳妥的
> 
> 我发现了，DEBUG 里 fcitx 多出来的几项是因为我安装了 fcitx5 更新器和几个插件，把插件和更新器都卸载之后，输出就只有一项了，但即便如此，安装模块后还是没有词库😂

……
是我的锅，刚刚我这边测试也是如此，我模块里面作的识别从来没考虑到 fcitx 还有其它插件，如果有这些插件，匹配数据的时候就会造成多个输出，这和我前面说的那些什么多用户多配置毫无关系，是我想当然了。

关于词库为什么不存在的问题我现在还没头绪，通常来说模块会把词库安装到 `/data/media/0/Android/data/org.fcitx.fcitx5.android/files/data/pinyin/dictionaries` 这个目录下，你看一下这里是不是有文件存在，以及，能否帮忙提供一下 adb shell 中你已有的那两个词库文件的详细路径？我再看看问题到底出在哪里。

**Comment by so1ar** [comment]
> 关于词库为什么不存在的问题我现在还没头绪

我好像找到问题所在了，magisk 模块里面的 customize.sh 脚本好像设置的文件路径不太对，解压缩后编辑这个文件，找到第 154 行，把 `cp -f $TMPDIR/data/dict $DICT_LOC` 改成 `cp -f $TMPDIR/dict/CustomPinyinDictionary_Fcitx.dict $DICT_LOC`，之后重新打包用 magisk 刷入就没问题了🤔。

**Comment by wuhgit** [comment]
> > 关于词库为什么不存在的问题我现在还没头绪
> 
> 我好像找到问题所在了，magisk 模块里面的 customize.sh 脚本好像设置的文件路径不太对，解压缩后编辑这个文件，找到第 154 行，把 `cp -f $TMPDIR/data/dict $DICT_LOC` 改成 `cp -f $TMPDIR/dict/CustomPinyinDictionary_Fcitx.dict $DICT_LOC`，之后重新打包用 magisk 刷入就没问题了🤔。

感谢！

问题根源找到了，20240517 为修复 KernelSu 模块的问题动了太多代码，整合的时候疏忽了，把最开始的模块生成代码合并了进来，当时还造成了模块zip后缀丢失的问题，没想到路径这一块也出问题了。

话说回来，这几版模块放出来好久了都没发现问题，也没人反馈，看来是真没几个人用 😅
