### ISSUE TITLE
大佬能提供下txt的词库吗？双拼用户用不了这词库😭

### ISSUE THREAD

**Issue by SunflowerThom** [wuhgit/CustomPinyinDictionary#6]

**Comment by choyy** [comment]
双拼不能用拼音的词库吗？（来自刚用双拼一周的用户的疑问）

**Comment by choyy** [comment]
[自定义词库 - ArchWiki](https://wiki.archlinux.org/title/Fcitx5_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%BA%93)
这个可以将 dict 转为 txt，示例：
`libime_pinyindict -d name.dict name.txt`

**Comment by SunflowerThom** [comment]
> 双拼不能用拼音的词库吗？（来自刚用双拼一周的用户的疑问）

会混乱 比如我用小鹤打 “吃水”是“ii uv” 如果有全拼词库就会显示“是谁”“嗜睡”之类的 非常不利于选词

**Comment by SunflowerThom** [comment]
> [自定义词库 - ArchWiki](https://wiki.archlinux.org/title/Fcitx5_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%BA%93) 这个可以将 dict 转为 txt，示例： `libime_pinyindict -d name.dict name.txt`

这行命令是直接用cdm直接转还是安装sql之类软件再转呀

**Comment by choyy** [comment]
> > 双拼不能用拼音的词库吗？（来自刚用双拼一周的用户的疑问）
> 
> 会混乱 比如我用小鹤打 “吃水”是“ii uv” 如果有全拼词库就会显示“是谁”“嗜睡”之类的 非常不利于选词

![图片](https://user-images.githubusercontent.com/68107073/161363725-86149c52-9e0a-4662-8f24-e2a7d84eab99.png)
好像没有哎

**Comment by choyy** [comment]
> > [自定义词库 - ArchWiki](https://wiki.archlinux.org/title/Fcitx5_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%BA%93) 这个可以将 dict 转为 txt，示例： `libime_pinyindict -d name.dict name.txt`
> 
> 这行命令是直接用cdm直接转还是安装sql之类软件再转呀

呃。。。linux命令行
我发一份吧
[https://cowtransfer.com/s/9834260ddc7044](https://cowtransfer.com/s/9834260ddc7044)
话说你是要手动修改 txt 文件吗

**Comment by wuhgit** [comment]
@SunflowerThom 

很抱歉，我对双拼基本没有什么了解，印象里不同的双拼方案的编码也不一样，所以一直没有提供双拼版本的词库。

不过你可以通过相关的转换工具把 Fcitx5 的全拼词库转换到 txt 然后再根据自己的需求进行修改。choyy 已经给出相关的方法了，你可以试试。

**Comment by SunflowerThom** [comment]
> > > [自定义词库 - ArchWiki](https://wiki.archlinux.org/title/Fcitx5_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%BA%93) 这个可以将 dict 转为 txt，示例： `libime_pinyindict -d name.dict name.txt`
> > 
> > 
> > 这行命令是直接用cdm直接转还是安装sql之类软件再转呀
> 
> 呃。。。linux命令行 我发一份吧 https://cowtransfer.com/s/9834260ddc7044 bbfkgn 话说你是要手动修改 txt 文件吗

谢啦 用深蓝可以转换哈

**Comment by SunflowerThom** [comment]
> @SunflowerThom
> 
> 很抱歉，我对双拼基本没有什么了解，印象里不同的双拼方案的编码也不一样，所以一直没有提供双拼版本的词库。
> 
> 不过你可以通过相关的转换工具把 Fcitx5 的全拼词库转换到 txt 然后再根据自己的需求进行修改。choyy 已经给出相关的方法了，你可以试试。

嗯嗯 上面有热心朋友弄好了
