### ISSUE TITLE
您好,考虑添加方言词库吗

### ISSUE THREAD

**Issue by qxqzx3489** [wuhgit/CustomPinyinDictionary#7]
您好,可以添加方言词库吗

**Comment by qxqzx3489** [comment]
您好，如果我刷了这个模块之后我自己的词库我要怎么加上呢

**Comment by wuhgit** [comment]
由于您没说是哪一个输入法，我默认您说的是 Gboard


> 您好,可以添加方言词库吗

方言也有很多种啊，这个似乎很特例化，不一定适用所有人，所以目前应该是不会考虑这个。


> 您好，如果我刷了这个模块之后我自己的词库我要怎么加上呢

请问你自己的词库也是 `PersonalDictionary.db` 类型的吗？如果是，那只能是二选一了，或者你可以自己合并。如果不是，应该不影响你使用自己的词库，其实准确的描述，`PersonalDictionary.db` 这个类型的词库应该被称为自定义短语，和实际的输入法词库不是一回事。

**Comment by qxqzx3489** [comment]
> 

好的,感谢回复
