### ISSUE TITLE
字典中可以看到词语，但输入法使用时未生效

### ISSUE THREAD

**Issue by Be-Naive** [wuhgit/CustomPinyinDictionary#8]
安装完成后没有任何类似改善用户输入的提示，经过一段时间等待后输入法使用时词库仍然未生效。

**Comment by wuhgit** [comment]
改善用户输入的提示只是可能会出现。

另外请提供更详细的信息，比如 Gboard 版本，Android 系统版本，Magisk 版本等。

**Comment by wuhgit** [comment]
超过20天没有回复，暂时关闭。
后续有反馈或者更新，可以重开。
